let productos = [
    {
        "id": 1,
        "name": "Tres leches de fresa",
        "descripcion": "Pastel de 3 leches, bizcocho de vainilla, relleno de fresa con crema batida y cobertura de fresas con crema batida.",
        "numeroDePersonas": 15,
        "relleno": "crema batida con fresas",
        "cobertura": "crema batida con fresas",
        "pan": "vainilla",
        "img": null,
        "precio": 440,
        "createdAt": null
    },
    {
        "id": 2,
        "name": "Tres leches de durazno",
        "descripcion": "Pastel de 3 leches, bizcocho de vainilla, relleno de durazno con crema batida y cobertura de duraznos con crema batida.",
        "numeroDePersonas": 15,
        "relleno": "crema batida con durazno",
        "cobertura": "crema batida con durazno",
        "pan": "vainilla",
        "img": null,
        "precio": 420,
        "createdAt": null
    },
    {
        "id": 3,
        "name": "Tres leches de frutos rojos",
        "descripcion": "Pastel de 3 leches, bizcocho de vainilla, relleno de frutos rojos con crema batida y cobertura de mermelada de frutos rojos y crema batida.",
        "numeroDePersonas": 15,
        "relleno": "crema batida con frutos rojos",
        "cobertura": "crema batida con mermelada de frutos rojos",
        "pan": "vainilla",
        "img": null,
        "precio": 420,
        "createdAt": null
    },
    {
        "id": 4,
        "name": "Tres leches de nuez",
        "descripcion": "Pastel de 3 leches, bizcocho de vainilla, relleno de nuez con crema batida y cobertura de nuez con crema batida.",
        "numeroDePersonas": 15,
        "relleno": "crema batida con nuez",
        "cobertura": "crema batida con nuez",
        "pan": "vainilla",
        "img": null,
        "precio": 420,
        "createdAt": null
    },
    {
        "id": 5,
        "name": "Tres leches de oreo",
        "descripcion": "Pastel de 3 leches, bizcocho de vainilla, relleno de oreo con crema batida de chocolate y cobertura de crema batida de chocolate y oreo.",
        "numeroDePersonas": 15,
        "relleno": "crema batida de chocolate y oreo",
        "cobertura": "crema batida de chocolate y oreo",
        "pan": "vainilla",
        "img": null,
        "precio": 420,
        "createdAt": null
    },
    {
        "id": 6,
        "name": "Tres leches de chocolate con oreo",
        "descripcion": "Pastel de 3 leches, bizcocho de chocolate, relleno de oreo con crema batida y cobertura de crema batida de chocolate y oreo.",
        "numeroDePersonas": 15,
        "relleno": "crema batida de chocolate y oreo",
        "cobertura": "crema batida de chocolate y oreo",
        "pan": "chocolate",
        "img": null,
        "precio": 420,
        "createdAt": null
    },
    {
        "id": 7,
        "name": "Tres leches de chocolate con fresa",
        "descripcion": "Pastel de 3 leches, bizcocho de chocolate, relleno de fresa con crema batida y cobertura de fresa y crema batida de chocolate.",
        "numeroDePersonas": 15,
        "relleno": "crema batida con fresa",
        "cobertura": "crema batida de chocolate con fresa",
        "pan": "chocolate",
        "img": null,
        "precio": 440,
        "createdAt": null
    },
    {
        "id": 8,
        "name": "Tres leches de chocolate con frutos rojos",
        "descripcion": "Pastel de 3 leches, bizcocho de chocolate, relleno de frutos rojos con crema batida y cobertura de mermelada de frutos rojos y crema batida de chocolate.",
        "numeroDePersonas": 15,
        "relleno": "crema batida con frutos rojos",
        "cobertura": "crema batida de chocolate y mermelada de frutos rojos",
        "pan": "chocolate",
        "img": null,
        "precio": 420,
        "createdAt": null
    },
    {
        "id": 9,
        "name": "Tres leches con rompope",
        "descripcion": "Pastel de 3 leches, bizcocho de vainilla, relleno de rompope con nuez, crema batida y cobertura de crema batida con nuez.",
        "numeroDePersonas": 15,
        "relleno": "crema batida con rompope y nuez",
        "cobertura": "crema batida con nuez",
        "pan": "vainilla",
        "img": null,
        "precio": 480,
        "createdAt": null
    },
    {
        "id": 10,
        "name": "Tres leches y crema de coco",
        "descripcion": "Pastel de 3 leches y crema de coco, bizcocho de vainilla, relleno de coco, queso crema y cobertura de crema batida y coco rallado.",
        "numeroDePersonas": 15,
        "relleno": "coco y queso crema",
        "cobertura": "crema batida y coco rallado",
        "pan": "vainilla",
        "img": null,
        "precio": 420,
        "createdAt": null
    },
    {
        "id": 11,
        "name": "Matilda",
        "descripcion": "Pastel Matilda, pan de chocolate tipo americano, relleno y decorado con ganache de chocolate Turin semiamargo.",
        "numeroDePersonas": 15,
        "relleno": "ganache de chocolate Turin semiamargo",
        "cobertura": "ganache de chocolate Turin semiamargo",
        "pan": "chocolate tipo americano",
        "img": null,
        "precio": 520,
        "createdAt": null
    },
    {
        "id": 12,
        "name": "Flan",
        "descripcion": "Flan clásico",
        "numeroDePersonas": 12,
        "relleno": null,
        "cobertura": null,
        "pan": null,
        "img": null,
        "precio": 320,
        "createdAt": null
    }
]
